language: node_js
node_js:
  - "stable"
sudo: required
services:
  - docker
before_script:
  - npm install
script:
  - docker build -t node-app .
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag node-app $DOCKER_USERNAME/node-app:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USERNAME/node-app:$TRAVIS_BUILD_NUMBER
  - docker tag node-app $DOCKER_USERNAME/node-app:latest
  - docker push $DOCKER_USERNAME/node-app:latest